cities:
  - id: paris
    name: Paris
    country: France
    region: europe

  - id: tokyo
    name: Tokyo
    country: Japan
    region: asia

  - id: cairo
    name: Cairo
    country: Egypt
    region: africa

  - id: london
    name: London
    country: United Kingdom
    region: europe

  - id: rome
    name: Rome
    country: Italy
    region: europe

  - id: berlin
    name: Berlin
    country: Germany
    region: europe

  - id: sydney
    name: Sydney
    country: Australia
    region: oceania

  - id: moscow
    name: Moscow
    country: Russia
    region: europe
