suspects:
  - id: viktor
    name: Albert E. Katt
    gender: male
    hair: dark
    hobby: intellectual

  - id: marcus
    name: Ron Turn
    gender: male
    hair: dark
    hobby: physical

  - id: sebastian
    name: Benjamin Hanna
    gender: male
    hair: light
    hobby: intellectual

  - id: dimitri
    name: Valentin E. Gurl
    gender: male
    hair: light
    hobby: physical

  - id: mei
    name: Amanda Hugginkiss
    gender: female
    hair: dark
    hobby: intellectual

  - id: natasha
    name: Natasha Petrova
    gender: female
    hair: dark
    hobby: physical

  - id: scarlett
    name: Rikki D. Khan-Struckshun
    gender: female
    hair: light
    hobby: intellectual

  - id: isabella
    name: Cole Fyre-Doven
    gender: female
    hair: light
    hobby: physical
