# Random phrases appended to witness clues to reinforce threatening atmosphere
witness_closing_phrases:
  - "That's all I know, I swear!"
  - "Please, don't hurt me!"
  - "I've told you everything!"
  - "I don't know anything else!"
  - "That's everything, I promise!"
  - "You gotta believe me!"
  - "I'm just a bystander!"
  - "Don't shoot the messenger!"
  - "That's all I saw, honest!"
  - "I wish I knew more!"
  - "Please, I have a family!"
  - "That's the truth, I swear it!"
